---
title: Bastille Agency
timezone: UTC
collections:
  candidate-faqs:
    title: Candidate FAQs
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
domain: http://www.bastilleagency.com
permalink: pretty
exclude:
- node_modules
github:
  access_token: 7681ed28eb73b6279d73631e9c669e2d98d1309f
  path: bastilleagency/bastille
  branch: master
  format: compiled
simple_form:
  api_token: 1868f956781ecec5fc09bbb2e8ba4993
